# APPLICATION
application:
  name: crypto_market_intelligence
  pipeline_name: crypto_market_etl
  source_system: coingecko
  target_table: crypto_market 
  raw_dataset: crypto_market

# AWS
aws: 
  region: ap-south-1

# COINGECKO 
coingecko: 
  base_url: ""
  vs_currency: usd

# SNS
sns:
  topic_arn:

# S3
s3:
  bucket: crypto-etl-bucket
  raw_prefix: raw_data
  processed_prefix: processed_data

# REDSHIFT
redshift:
  host:
  port:
  database:
  schema:
  table:
  workgroup:
  iam_role:

# EMR
emr:
  release: 
  service_role:
  ec2_role:
  instance_profile:

  subnet_id:

  master_instance_type:
  core_instance_type:
  core_instance_count: 1

  cluster_name:
  log_uri:

# RUNTIME
runtime:
  compute_mode: production
  timezone:
  dry_run:
  log_level:
  log_dir:

